force-app/main/default/objects/ReportingData__c/fields/CRM_Category__c.field-meta.xml
<CustomField>
    <fullName>CRM_Category__c</fullName>
    <description>Reporting Category</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Adoption</fullName>
            </value>
            <value>
                <fullName>New Users</fullName>
            </value>
            <value>
                <fullName>Service Appointment</fullName>
            </value>
            <value>
                <fullName>DIA User Adoption</fullName>
            </value>
            <value>
                <fullName>STO</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NKS_ChatAfterWork.cls
public with sharing class NKS_ChatAfterWork {
    @AuraEnabled
    public static Id reportThreatClick() {
        try {
            ReportingData__c rData = new ReportingData__c();
            rData.CRM_Category__c = 'Chat Threat';
            insert rData;
            return rData.Id;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void updateThreatClickValue(Id rDataId, Integer value) {
        try {
            ReportingData__c rData = new ReportingData__c(Id = rDataId);
            rData.CRM_Value__c = value;
            update rData;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}